// <auto-generated />
using System;
using Financeiro.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financeiro.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinanceiroDbContext))]
    [Migration("20260925165452_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Financeiro.Domain.Vendas.VendaFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_CANCELAMENTO");

                    b.Property<DateTime?>("DataQuitacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_QUITACAO");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_RECEBIMENTO");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_VENDA");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FORMA_PAGAMENTO");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MOTIVO_CANCELAMENTO");

                    b.Property<string>("OrigemCancelamento")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ORIGEM_CANCELAMENTO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("VALOR_TOTAL");

                    b.Property<int>("VendaId")
                        .HasColumnType("int")
                        .HasColumnName("VENDA_ID");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VERSAO");

                    b.HasKey("Id");

                    b.HasIndex("DataVenda")
                        .HasDatabaseName("IX_VENDA_FINANCEIRA_DATA_VENDA");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_VENDA_FINANCEIRA_STATUS");

                    b.HasIndex("VendaId")
                        .IsUnique()
                        .HasDatabaseName("UQ_VENDA_FINANCEIRA_VENDA_ID");

                    b.ToTable("VENDA_FINANCEIRA", (string)null);
                });

            modelBuilder.Entity("Financeiro.Domain.Vendas.VendaFinanceiraItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("DESCRICAO");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("PRECO_UNITARIO");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUTO_ID");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("VALOR_TOTAL");

                    b.Property<int>("VendaFinanceiraId")
                        .HasColumnType("int")
                        .HasColumnName("VENDA_FINANCEIRA_ID");

                    b.HasKey("Id");

                    b.HasIndex("VendaFinanceiraId");

                    b.ToTable("VENDA_FINANCEIRA_ITEM", (string)null);
                });

            modelBuilder.Entity("Financeiro.Infrastructure.Persistence.Outbox.OutboxNotificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTEUDO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ENVIO");

                    b.Property<DateTime>("ProximaTentativa")
                        .HasColumnType("datetime2")
                        .HasColumnName("PROXIMA_TENTATIVA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS");

                    b.Property<int>("Tentativas")
                        .HasColumnType("int")
                        .HasColumnName("TENTATIVAS");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TIPO");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ULTIMO_ERRO");

                    b.Property<int>("VendaId")
                        .HasColumnType("int")
                        .HasColumnName("VENDA_ID");

                    b.HasKey("Id");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("IX_OUTBOX_NOTIFICACAO_VENDA");

                    b.HasIndex("Status", "ProximaTentativa")
                        .HasDatabaseName("IX_OUTBOX_NOTIFICACAO_PENDENTES");

                    b.ToTable("OUTBOX_NOTIFICACAO", (string)null);
                });

            modelBuilder.Entity("Financeiro.Domain.Vendas.VendaFinanceira", b =>
                {
                    b.OwnsOne("Financeiro.Domain.Vendas.ClienteVenda", "Cliente", b1 =>
                        {
                            b1.Property<int>("VendaFinanceiraId")
                                .HasColumnType("int");

                            b1.Property<int>("ClienteId")
                                .HasColumnType("int")
                                .HasColumnName("CLIENTE_ID");

                            b1.Property<string>("Documento")
                                .IsRequired()
                                .HasMaxLength(18)
                                .HasColumnType("nvarchar(18)")
                                .HasColumnName("CLIENTE_DOCUMENTO");

                            b1.Property<string>("Email")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("CLIENTE_EMAIL");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("CLIENTE_NOME");

                            b1.HasKey("VendaFinanceiraId");

                            b1.ToTable("VENDA_FINANCEIRA");

                            b1.WithOwner()
                                .HasForeignKey("VendaFinanceiraId");
                        });

                    b.Navigation("Cliente")
                        .IsRequired();
                });

            modelBuilder.Entity("Financeiro.Domain.Vendas.VendaFinanceiraItem", b =>
                {
                    b.HasOne("Financeiro.Domain.Vendas.VendaFinanceira", null)
                        .WithMany("Itens")
                        .HasForeignKey("VendaFinanceiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Financeiro.Domain.Vendas.VendaFinanceira", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
